# Generated by Django 5.1.1 on 2024-10-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProtectoraProtectoraProtectora',
            new_name='Colaborador',
        ),
    ]
